version: '3.8'
services:
  postgresdb:
    image: postgres:14.1-alpine
    container_name: postgres-test-app
    restart: always
    environment:
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_DATABASE_NAME}
    ports:
      - '1234:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_net
  app:
    container_name: go-test-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8080:8080'
    depends_on:
      - postgresdb
    networks:
      - app_net
volumes:
  db:
    driver: local
networks:
  app_net:
    driver: bridge