// Code generated by MockGen. DO NOT EDIT.
// Source: /home/quark/alif/internal/domain/account/query/dao.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Elementary1092/test_banking/internal/domain/account/query/model"
	gomock "github.com/golang/mock/gomock"
)

// MockReadDAO is a mock of ReadDAO interface.
type MockReadDAO struct {
	ctrl     *gomock.Controller
	recorder *MockReadDAOMockRecorder
}

// MockReadDAOMockRecorder is the mock recorder for MockReadDAO.
type MockReadDAOMockRecorder struct {
	mock *MockReadDAO
}

// NewMockReadDAO creates a new mock instance.
func NewMockReadDAO(ctrl *gomock.Controller) *MockReadDAO {
	mock := &MockReadDAO{ctrl: ctrl}
	mock.recorder = &MockReadDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadDAO) EXPECT() *MockReadDAOMockRecorder {
	return m.recorder
}

// FindAccount mocks base method.
func (m *MockReadDAO) FindAccount(ctx context.Context, params map[string]string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccount", ctx, params)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccount indicates an expected call of FindAccount.
func (mr *MockReadDAOMockRecorder) FindAccount(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccount", reflect.TypeOf((*MockReadDAO)(nil).FindAccount), ctx, params)
}

// FindAllTransactions mocks base method.
func (m *MockReadDAO) FindAllTransactions(ctx context.Context, accountNumber string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTransactions", ctx, accountNumber)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTransactions indicates an expected call of FindAllTransactions.
func (mr *MockReadDAOMockRecorder) FindAllTransactions(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTransactions", reflect.TypeOf((*MockReadDAO)(nil).FindAllTransactions), ctx, accountNumber)
}

// FindInTransactions mocks base method.
func (m *MockReadDAO) FindInTransactions(ctx context.Context, accountNumber string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInTransactions", ctx, accountNumber)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInTransactions indicates an expected call of FindInTransactions.
func (mr *MockReadDAOMockRecorder) FindInTransactions(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInTransactions", reflect.TypeOf((*MockReadDAO)(nil).FindInTransactions), ctx, accountNumber)
}

// FindOutTransactions mocks base method.
func (m *MockReadDAO) FindOutTransactions(ctx context.Context, accountNumber string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOutTransactions", ctx, accountNumber)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOutTransactions indicates an expected call of FindOutTransactions.
func (mr *MockReadDAOMockRecorder) FindOutTransactions(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOutTransactions", reflect.TypeOf((*MockReadDAO)(nil).FindOutTransactions), ctx, accountNumber)
}
