// Code generated by MockGen. DO NOT EDIT.
// Source: /home/quark/alif/internal/domain/customer/query/dao.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Elementary1092/test_banking/internal/domain/customer/query/model"
	gomock "github.com/golang/mock/gomock"
)

// MockReadDAO is a mock of ReadDAO interface.
type MockReadDAO struct {
	ctrl     *gomock.Controller
	recorder *MockReadDAOMockRecorder
}

// MockReadDAOMockRecorder is the mock recorder for MockReadDAO.
type MockReadDAOMockRecorder struct {
	mock *MockReadDAO
}

// NewMockReadDAO creates a new mock instance.
func NewMockReadDAO(ctrl *gomock.Controller) *MockReadDAO {
	mock := &MockReadDAO{ctrl: ctrl}
	mock.recorder = &MockReadDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadDAO) EXPECT() *MockReadDAOMockRecorder {
	return m.recorder
}

// FindCustomer mocks base method.
func (m *MockReadDAO) FindCustomer(ctx context.Context, filter map[string]string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCustomer", ctx, filter)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCustomer indicates an expected call of FindCustomer.
func (mr *MockReadDAOMockRecorder) FindCustomer(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCustomer", reflect.TypeOf((*MockReadDAO)(nil).FindCustomer), ctx, filter)
}
